keep-source-folder: true
clustered: false
namespaces:
  - default
  - tvk
logLevel: INFO
kubeConfig: "invalid/path/to/kubeconfig"
labels:
  - matchLabels:
      "app": "frontend"
      "custom": "label"
  - matchLabels:
      "app": "backend"
gvks:
  - group: ""
    version: ""
    kind: pod
  - group: apps
    version: ""
    kind: Deployment
